### ISSUE TITLE
getting "Cannot complete value of unexpected type X" error with children

### ISSUE THREAD

**Issue by jaredh159** [alexsteinerde/graphql-kit#10]
I'm having trouble resolving the children of a model.  I definitely might be doing something super dumb though.  What's odd is, in my other vapor/graphql app (yes, I have two now...) I haven't hit this problem, but I use parent/children a decent bit.  Anyway, I have models like this:

```swift
final class Order: Model, Content {
  static let schema = "orders"

  @ID(key: .id)
  var id: UUID?

  @Field(key: "email")
  var email: String

  @Children(for: \OrderItem.$order)
  var items: [OrderItem]

  init() {}
}

final class OrderItem: Model, Content {
  static let schema = "order_items"

  @ID(key: .id)
  var id: UUID?

  @Parent(key: "order_id")
  var order: Order

  @Field(key: "title")
  var title: String

  init() {}
}
```

The schema looks like this:

```swift
let AppSchema = try! Graphiti.Schema<Resolver, Request> {
  Scalar(UUID.self)

  Type(Order.self) {
    Field("id", at: \.id)
    Field("email", at: \.email)
    Field("items", with: \.$items)
  }

  Type(OrderItem.self) {
    Field("title", at: \.title)
    Field("order", with: \.$order)
  }

  Query {
    Field("getOrder", at: Resolver.getOrder) {
      Argument("id", at: \.id)
    }
  }
}
```

And the resolver looks like this:

```swift
final class Resolver {
  struct IdentifyEntityArgs: Codable {
    let id: UUID
  }

  func getOrder(
    request: Request,
    args: IdentifyEntityArgs
  ) throws -> Future<Order> {
    return Order.query(on: request.db)
      .with(\.$items)
      .filter(\.$id == args.id)
      .first()
      .unwrap(or: Abort(.notFound))
  }
}
```

But when I send a graphql query like so:

```gql
query {
  order: getOrder(id: "FBF9C172-E57E-49A8-8806-85F6C923E55A") {
    id
    items {
      title # <-- trying to get one of the children causes the error, without this, it works
    }
  }
}
```

I get the error `Cannot complete value of unexpected type \"OrderItem\".`

I feel like I'm missing something stupid.  I think I'm sort of following your examples for users/todos in the readme.

If the code above isn't clear enough, I've created a [super minimal reproduction repository](https://github.com/jaredh159/graphql-kit-test-app) using an in-memory sql-lite db.  If you want to take a look, you can just clone the repo, then run `swift run` and (in another terminal tab) try `bash ./test-error.sh` to send the query shown above.

**Comment by jaredh159** [comment]
Sure enough, that completely fixes it.  Although I can't say that I understand fully why.  It seems like there's a _very explicit_ registration of the `OrderItem` type in the schema, when I define it as a GraphQL type using `Type(OrderItem.self) { ...` on t[his line](https://github.com/jaredh159/graphql-kit-test-app/blob/master/Sources/App/GraphQL/Schema.swift#L9).  But I'm probably still missing a something.  

Really appreciate the help, as always.

**Comment by alexsteinerde** [comment]
I agree, this doesn't seem perfect from an API perspective. But I also don't know enough about the Graphiti implementation so I can't explain the reason for this. 
Maybe there will be a better way in the future.
