### ISSUE TITLE
Get pivots

### ISSUE THREAD

**Issue by ZirgVoice** [alexsteinerde/graphql-kit#11]
Hi, can you tell me how to get pivot?
I tried this but it gives the error "Unknown kind of type: TodoTag"
```swift
Type(Todo.self) {
    Field("id", at: \.id)
    Field("title", at: \.title)
    Field("user", with: \.$user)
    Field("tags", with: \.$tags.$pivots)
}
```

**Comment by alexsteinerde** [comment]
Please make sure to register the `TodoTag` GraphQL type with `Types(TodoTag.self)` in your schema.
Example: https://github.com/GraphQLSwift/Graphiti/blob/af903a243862c6427935677b91f67df0c21f2a71/Tests/GraphitiTests/StarWarsAPI/StarWarsAPI.swift#L101

**Comment by ZirgVoice** [comment]
Thanks a lot, added `Types (Todo Tag.self)` and it worked
