### ISSUE TITLE
Date error

### ISSUE THREAD

**Issue by ZirgVoice** [alexsteinerde/graphql-kit#15]
When trying to send a date as an argument, I get the error `"The data couldn't be read because it isn't in the correct format."` At the same time, the date from the database is decoded normally. If `Scalar(Date.self)` is changed to `DateScalar(formatter: ISO8601DateFormatter())`, the error becomes: `"Argument \"date\" got invalid value 670427457.\nExpected type \"Date\", found 670427457."`. I send the date in ISO 8601 format `"2022-03-31T13:50:57Z"`

**Comment by maximkrouk** [comment]
Are you sending mutations? Seems like queries should work as expected...

**Comment by ZirgVoice** [comment]
The problem is in graphiti, in the graphiti-1.0.0 branch everything works as it should

**Comment by alexsteinerde** [comment]
@ZirgVoice Right. Graphiti introduced the support of custom encoders recently with a version bump to 1.0.0. 
I think we should bump the required Graphiti version to 1.0.0 as I did in the graphiti-1.0.0 branch.
Would you be fine with this?

**Comment by ZirgVoice** [comment]
@alexsteinerde Yes, great, thanks
