### ISSUE TITLE
Selection Set from the Resolver

### ISSUE THREAD

**Issue by Samsv77** [alexsteinerde/graphql-kit#20]
Hi,
I would need to get access to the Selection Set from the Resolver.
Do you think it is hard to implement ?
The selectionSet is a flat list of the fields that the user requested, for example,

```
family {
   name
   child {
     name
  }
}
```

Would give the selectionSet `["name", "child/name"]`

Thank you

**Comment by alexsteinerde** [comment]
This is an implementation detail of `Graphiti`. And I saw you already created an issue over there: https://github.com/GraphQLSwift/Graphiti/issues/104.
So I'll close this issue as it is not relevant to this package.
