### ISSUE TITLE
Registered GraphQL Schema ignores authenticators

### ISSUE THREAD

**Issue by bdrelling** [alexsteinerde/graphql-kit#22]
The following code (using a simple `UserAuthenticator` example from [Vapor's Authentication Docs](https://docs.vapor.codes/security/authentication/)) does not respect the authenticator:

```swift
routes.grouped(UserAuthenticator()).register(graphQLSchema: schema, withResolver: resolver)
```

I believe the same would hold true for any sort of Vapor middleware, but have only tested the authenticator.

**Comment by bdrelling** [comment]
Nevermind, this was just the result of configuring the `GuardMiddleware` incorrectly. Closing this issue, sorry!

**Comment by Fa1zer** [comment]
Hi! I have same problem. Can you please tell me exactly what your mistake was?

**Comment by bdrelling** [comment]
Oof, I don't remember at all, sorry! I think I just needed to re-read the documentation in this case a bit more closely, otherwise I would have included more information on the Issue.

Good luck! Sorry I don't have more info.
