### ISSUE TITLE
Enum in GraphQL schema

### ISSUE THREAD

**Issue by Fa1zer** [alexsteinerde/graphql-kit#25]
Hi, I'm trying to use enum in my GraphQL schema. But I get the following error.
<img width="1212" alt="Снимок экрана 2023-08-02 в 11 27 21" src="https://github.com/alexsteinerde/graphql-kit/assets/86740278/b9cebea4-30a1-454c-9fa0-135e6bf1e4ee">
I did everything just like it says in README.md
My code:
```
import Fluent

enum FamilyStatus: String, Codable, CaseIterable {
    case Free
    case inRelationships = "In Relationships"
    case inFreeRelationships = "In Free Relationships"
    case allAreComplicated = "All Are Complicated"
    
    static func migrate(_ db: Database) async throws {
        _ = try await db.enum("family_status")
            .case(FamilyStatus.Free.rawValue)
            .case("inRelationships")
            .case("inFreeRelationships")
            .case("allAreComplicated")
            .create()
    }
}
```

`Enum(FamilyStatus.self)`

What is my mistake and how do I fix it?

**Comment by Fa1zer** [comment]
I checked StarWarAPI file in Graphiti package and find this:
```
Enum(Episode.self) {
            Value(.newHope)
                .description("Released in 1977.")

            Value(.empire)
                .description("Released in 1980.")

            Value(.jedi)
                .description("Released in 1983.")
        }
        .description("One of the films in the Star Wars Trilogy.")
```
It fixed my problem too, but I don't understand why README.md shows a different solution. I think it is misleading for the developer and should be corrected by inserting code similar to the code from StarWarsAPI.

**Comment by alexsteinerde** [comment]
You were probably missing the import of `GraphQLKit` because the extension on `Enum` that allows the quick registration of enums via `CaseIterable` is available in that package.
I added a test case to demonstrate the usage: https://github.com/alexsteinerde/graphql-kit/commit/e17518fb0ef1073876fadafd15cc3a5dba1e56aa.
