### ISSUE TITLE
Can't add parent and child fields to schema due to circular dependency 

### ISSUE THREAD

**Issue by cameroncooke** [alexsteinerde/graphql-kit#26]
Given this slightly reworked example:

```swift
final class User: Model {
    ...
    
    @Children(for: \.$user)
    var todos: [Todo]
    
    ...
}

final class Todo: Model {
    ...
    
    @Parent(key: "user_id")
    var user: User
    
    ...
}
```

```swift
// Schema types
Type(Todo.self) {
    Field("user", with: \.$user)
}

Type(User.self) {
    Field("todos", with: \.$todos)
}
```

I get the following error:

> Fatal error: 'try!' expression unexpectedly raised an error: Type "User" was referenced but not defined.

This seems to be because `User` needs to be defined in the schema before `Todo` for Todo's `@Parent` relation, but `Todo` also needs to be defined before `User` for User's `@Children` relation. Essentially we have a circular dependency issue.

**Comment by alexsteinerde** [comment]
Please have a look at the StarWars example from Graphiti: https://github.com/GraphQLSwift/Graphiti/blob/3a4b6c56b47979497c9ae511e14e455064e1fc3f/Tests/GraphitiTests/StarWarsAPI/StarWarsAPI.swift#L26C50-L26C63
You have to use the `as: ` parameter when defining the reference and use the `TypeReference` Wrapper in both of your type definitions.

Does this fix your issue?

**Comment by cameroncooke** [comment]
Ah hadn't spotted that, I could find any documentation on these kinds of quirks. I will give it a go and let you know if that fixes my issue, thanks!

**Comment by alexsteinerde** [comment]
Yeah, I've had a look at the documentation of both Graphiti and GraphQL, but I couldn't find any mention of that either.
It's more learning by doing or by coping the examples.
Feel free to open an issue or PR on the Graphiti repo to extend the documentation there.

**Comment by cameroncooke** [comment]
So I'm still not able to get this working, the `as` parameter is not available when using the `with` parameter which is needed for the relation feature of this library which allows Vapor to automatically fetch child or parent objects.

**Comment by cameroncooke** [comment]
I've put together a demo app using almost identical example from the README https://github.com/cameroncooke/GraphQLTodoList

**Comment by cameroncooke** [comment]
The error I get is `Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Type "Todo" was referenced but not defined.`. I believe that Types have to be defined in the Scema before they can be referenced in the Scemea.

**Comment by alexsteinerde** [comment]
Ah, sorry, I overlooked that.
`TypeReference` is already used under the hood.
The real issue is, that the `Todo` is not references from the `Query` object. In Graphiti < 1.0.0 types would have to be mentioned in the `Query` object or manually via e.g. `Types(Todo.self)`*.

In Graphiti >= 1.0.0 this is no longer needed. 
The current version of this package still references Graphiti < 1.0.0 but you can use the latest version from the `master` branch where the updated Graphiti package is referenced. I didn't had the time to create a new proper version yet.
` .package(url: "https://github.com/alexsteinerde/graphql-kit.git", branch: "master"),`


*:
```swift
let schema = try! Schema<Resolver, Request> {
    Scalar(UUID.self)

    Type(Todo.self) {
        Field("user", with: \.$user)
    }

    Type(User.self) {
        Field("todos", with: \.$todos)
    }
    
    Types(Todo.self)

    Query {
        Field("users", at: Resolver.getAllUsers)
    }
}
```

**Comment by cameroncooke** [comment]
Thank you so much! That was it! Thought I was going crazy
